apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-backend
  namespace: student-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: student-backend
  template:
    metadata:
      labels:
        app: student-backend
    spec:
      containers:
        - name: student-backend
          image: ghcr.io/prasada7989/student-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: DB_HOST
              value: student.caxuyq6oov2w.us-east-1.rds.amazonaws.com
            - name: DB_USER
              value: admin
            - name: DB_PASSWORD
              valueFrom: prasad212
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_ROOT_PASSWORD
            - name: DB_NAME
              value: student
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: student-app
spec:
  selector:
    app: student-backend
  ports:
    - port: 5000
      targetPort: 5000
  type: ClusterIP
