apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-frontend
  namespace: student-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: student-frontend
  template:
    metadata:
      labels:
        app: student-frontend
    spec:
      containers:
        - name: student-frontend
          image: ghcr.io/prasada7989/student-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: student-app
spec:
  selector:
    app: student-frontend
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer
